package exception_handling;

public class Throw_exception_with_custom_message {
    public static void main(String[] args) {
        throw new ArithmeticException("Custom message for Arithmetic Exception");
    }
}
